# Generated by Django 4.1.7 on 2023-03-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='date',
        ),
        migrations.AddField(
            model_name='fish',
            name='model_label',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
